os: Visual Studio 2017

build_script:
 - cmd: dotnet restore src\RethinkDb.Driver.FSharp.sln
 - cmd: dotnet build -v n src\RethinkDb.Driver.FSharp.sln
 - cmd: dotnet pack src\RethinkDb.Driver.FSharp.sln -o %CD%\artifacts\nupkg
 
artifacts:
 - path: artifacts\nupkg\*.nupkg 

test: off

hosts:
  api.nuget.org: 93.184.221.200